# Generated by Django 3.1.7 on 2021-03-14 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='media/')),
                ('date_upload', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
