# Generated by Django 3.1.7 on 2021-03-15 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadAndDowloadApp', '0002_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arquivo',
        ),
        migrations.AddField(
            model_name='document',
            name='date_upload',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='media/'),
        ),
    ]
